version: '3.8'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: ejemplo
      POSTGRES_USER: bogarin
      POSTGRES_PASSWORD: bogarin
    ports:
      - "5432:5432"
    volumes:
      - postgres-db-data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: bogarin@example.com
      PGADMIN_DEFAULT_PASSWORD: bogarin
    depends_on:
      - postgres

volumes:
  postgres-db-data:
