spring:
    application:
        name: producto
    datasource:
        driver-class-name: org.postgresql.Driver
        hikari:
            connection-timeout: 2000
    jpa:
        hibernate:
            ddl-auto: update
appication:
    datasource:
        url: jdbc:postgresql://localhost:5432/ejemplo?user=bogarin&password=bogarin
    
    